linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - gomnd
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - varcheck
    - vet
